"""
The editor-side nudge that keeps this server's tools from going unused.

A deferred MCP tool is listed to the client by bare name, with its
description hidden until something asks for it. Nothing about repeating the
same mechanical edit five times in a row prompts that ask — see the incident
in docs/manual.md that motivated this file: `insert_case` sat unused for an
entire session, hand-edited duplicates of it collided across two parallel
edits, and the tool was only found because someone asked what it did.

A Claude Code `PreToolUse` hook on `Edit`/`Write` closes part of that gap by
injecting a reminder every time a manual edit is about to happen — but
`additionalContext` cannot block, and field evidence (docs/critical-review.md,
RF-13) showed a pure reminder gets habituated past by the third repetition:
54 files created in one session, 2 through this server. So there is a second,
narrower mechanism here: the one case where the hook payload alone proves a
manual `Write` is about to reinvent a pattern that already exists on disk —
a new file, in a directory where several siblings already share its
extension — is denied outright, naming `create_file(model_from=...)` in the
reason. Everything else stays advisory; the trigger is deliberately narrow
because it has to be false-positive free to be worth blocking on at all.

This module is every part of that: the reminder and the deny decision
(`hook_guard`), and the settings.json surgery that wires the hook up
(`init_hook`), so installing it is one command rather than a snippet to copy
by hand.
"""

from __future__ import annotations

import json
import sys
from difflib import SequenceMatcher
from pathlib import Path

# Substring used to recognise our own hook entry on a second run, and to
# avoid adding it twice. Deliberately just the command, not the whole JSON
# blob below, so a future wording change to REMINDER does not orphan the one
# already written to someone's settings.json.
MARKER = "mcp-bifrost hook-guard"

REMINDER = (
    "MANDATORY: before hand-editing, check whether a deferred "
    "mcp__bifrost__* tool fits better: insert_case (new switch branch), "
    "insert_symbol (new method/class beside an existing one), fix_symbol "
    "(rewrite one named symbol), fix_symbols (same change across many "
    "symbols), create_file+model_from (new file by analogy to a sibling), "
    "patch_group (atomic multi-file change). These are deferred — call "
    "ToolSearch for them; do not assume unavailable just because not listed."
)


# Below this many same-extension siblings, "matches an established pattern"
# is not a claim the hook payload alone can back up — one or two files could
# be coincidence, not a convention worth generating by analogy to.
MIN_SIBLINGS = 3


def _nearest_sibling(target_stem: str, siblings: list[Path]) -> Path:
    """
    The sibling to suggest as `model_from`, picked by name similarity to the
    file about to be created — a mechanical stand-in for "which existing file
    is this one most like", with no read of any file's content required.
    """
    return max(siblings,
              key=lambda p: SequenceMatcher(None, target_stem, p.stem).ratio())


def _deny_reason(payload: dict) -> str | None:
    """
    The one trigger this hook blocks on: `Write` to a file that does not yet
    exist, in a directory where `MIN_SIBLINGS` or more files already share
    its extension. Nothing here is a judgment call — existence and a
    directory listing are the whole check — so it is safe to deny rather
    than merely suggest. Returns the `permissionDecisionReason`, or None to
    fall through to the advisory reminder.
    """
    if payload.get("tool_name") != "Write":
        return None
    file_path = (payload.get("tool_input") or {}).get("file_path")
    if not file_path:
        return None

    target = Path(file_path)
    if target.exists():
        return None  # an existing file is what fix_symbol/fix_range are for

    try:
        siblings = [p for p in target.parent.iterdir()
                    if p.is_file() and p.suffix == target.suffix]
    except OSError:
        return None  # directory does not exist yet — nothing to pattern-match

    if len(siblings) < MIN_SIBLINGS:
        return None

    nearest = _nearest_sibling(target.stem, siblings)
    return (
        f"Blocked: {target.name} does not exist yet, and "
        f"{target.parent}/ already has {len(siblings)} other {target.suffix} "
        f"files. Use the deferred mcp__bifrost__create_file tool instead of "
        f"a raw Write — call ToolSearch for it if not listed — with "
        f"model_from={str(nearest)!r} so the new file is generated by "
        f"analogy to its closest-named neighbour instead of inventing this "
        f"directory's conventions from scratch."
    )


def hook_guard_output(payload: dict | None = None) -> dict:
    reason = _deny_reason(payload or {})
    if reason is not None:
        return {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": reason,
            }
        }
    return {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "additionalContext": REMINDER,
        }
    }


def _read_payload() -> dict:
    """
    The PreToolUse event Claude Code feeds this hook on stdin: `tool_name`
    and `tool_input` among other fields.

    `isatty()` guards against a hang: Claude Code always pipes JSON in, never
    a terminal, so a live stdin means this was invoked some other way (a
    shell, a test) and there is no payload to read. Anything unparseable
    degrades to "no payload" rather than raising — advisory-only is the safe
    failure mode for a hook that fires on every Edit/Write in the session.
    """
    if sys.stdin.isatty():
        return {}
    try:
        raw = sys.stdin.read()
    except (OSError, ValueError):
        return {}
    if not raw.strip():
        return {}
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {}


def hook_guard() -> int:
    """Entry point for `mcp-bifrost hook-guard`, invoked by the hook itself."""
    print(json.dumps(hook_guard_output(_read_payload())))
    return 0


def init_hook(settings_path: Path) -> str:
    """
    Merge a PreToolUse hook for `Edit|Write` into settings_path, additively.

    Additive on purpose: settings.json is shared with whatever else the user
    has wired up (other tools' hooks, permissions, models), so this only ever
    adds our one hook entry — an existing `Edit|Write` matcher keeps its
    other hooks, and every other matcher is untouched. Idempotent: run twice
    and the second run is a no-op.
    """
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    data = json.loads(settings_path.read_text()) if settings_path.exists() else {}

    pre = data.setdefault("hooks", {}).setdefault("PreToolUse", [])

    for block in pre:
        if block.get("matcher") == "Edit|Write":
            if any(MARKER in h.get("command", "")
                   for h in block.get("hooks", [])):
                return f"already present in {settings_path}"
            block.setdefault("hooks", []).append(
                {"type": "command", "command": MARKER})
            break
    else:
        pre.append({
            "matcher": "Edit|Write",
            "hooks": [{"type": "command", "command": MARKER}],
        })

    settings_path.write_text(json.dumps(data, indent=2) + "\n")
    return f"added to {settings_path}"


def init_hook_main(argv: list[str]) -> int:
    """Entry point for `mcp-bifrost init-hook`."""
    target = (Path.home() if "--global" in argv else Path.cwd()) \
        / ".claude" / "settings.json"
    print(f"mcp-bifrost: {init_hook(target)}")
    return 0
